env:
  node: true
  mocha: true
  es6: true
globals:
  Atomics: false
  SharedArrayBuffer: false
parser: ''
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - import
  - mocha
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:mocha/recommended
rules:
  array-bracket-newline:
    - error
    - consistent
  array-callback-return:
    - error
    - allowImplicit: false
  array-element-newline:
    - error
    - consistent
  callback-return:
    - off
  class-methods-use-this:
    - off
  comma-dangle:
    - error
    - always-multiline
  consistent-this:
    - off
  dot-location:
    - error
    - property
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  function-call-argument-newline:
    - off
  function-paren-newline:
    - error
    - consistent
  id-length:
    - off
  import/dynamic-import-chunkname:
    - error
  import/exports-last:
    - error
  import/extensions:
    - error
  import/first:
    - error
  import/group-exports:
    - off
  import/max-dependencies:
    - error
  import/newline-after-import:
    - error
  import/no-absolute-path:
    - error
  import/no-amd:
    - error
  import/no-anonymous-default-export:
    - error
  import/no-commonjs:
    - error
  import/no-cycle:
    - error
  import/no-default-export:
    - error
  import/no-deprecated:
    - error
  import/no-duplicates:
    - error
  import/no-dynamic-require:
    - error
  import/no-extraneous-dependencies:
    - off
  import/no-internal-modules:
    - off
  import/no-mutable-exports:
    - error
  import/no-named-as-default:
    - error
  import/no-named-as-default-member:
    - error
  import/no-named-default:
    - error
  import/no-named-export:
    - off
  import/no-namespace:
    - error
  import/no-nodejs-modules:
    - off
  import/no-relative-parent-imports:
    - off
  import/no-restricted-paths:
    - error
  import/no-self-import:
    - error
  import/no-unassigned-import:
    - error
  import/no-unused-modules:
    - error
  import/no-useless-path-segments:
    - error
  import/no-webpack-loader-syntax:
    - error
  import/order:
    - error
  import/prefer-default-export:
    - off
  import/unambiguous:
    - error
  indent:
    - error
    - 4
    - SwitchCase: 1
      flatTernaryExpressions: false
      ignoreComments: false
  linebreak-style:
    - error
    - unix
  max-len:
    - error
    - code: 120
  max-lines:
    - error
    - max: 500
      skipBlankLines: true
      skipComments: true
  max-lines-per-function:
    - error
    - max: 500
      skipBlankLines: true
      skipComments: true
      IIFEs: true
  max-params:
    - error
    - max: 4
  max-statements:
    - error
    - 40
  mocha/no-exclusive-tests:
    - error
  mocha/no-hooks:
    - error
  mocha/no-hooks-for-single-case:
    - error
  mocha/no-mocha-arrows:
    - off
  mocha/no-pending-tests:
    - error
  mocha/no-return-from-async:
    - error
  mocha/no-skipped-tests:
    - error
  mocha/no-synchronous-tests:
    - error
  mocha/no-top-level-hooks:
    - error
  mocha/prefer-arrow-callback:
    - error
    - allowNamedFunctions: false
      allowUnboundThis: false
  multiline-ternary:
    - off
  no-bitwise:
    - off
  no-constant-condition:
    - error
    - checkLoops: false
  no-magic-numbers:
    - off
  no-mixed-operators:
    - off
  no-plusplus:
    - off
  no-ternary:
    - off
  no-undefined:
    - off
  no-unused-vars:
    - error
    - args: none
  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: true
      allowMultiplePropertiesPerLine: false
  one-var:
    - error
    - never
  padded-blocks:
    - off
  prefer-destructuring:
    - off
  prefer-regex-literals:
    - off
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
  require-await:
    - off
  semi:
    - error
    - always
  sort-imports:
    - off
  sort-keys:
    - error
    - asc
    - caseSensitive: false
      natural: true
      minKeys: 2
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
  strict:
    - error
    - never
