env:
  node: true
  es6: true
globals:
  Atomics: false
  SharedArrayBuffer: false
overrides:
  - extends:
      - "@acme/eslint-config/typescript"
    excludedFiles:
      - "*.test.ts"
    files:
      - "*.ts"
      - "*.tsx"
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: "./tsconfig.eslint.json"
    plugins:
      - "@typescript-eslint"
  - env:
      jest: true
    extends:
      - "@acme/eslint-config/jest"
    files:
      - "*.test.ts"
    plugins:
      - jest
      - "@typescript-eslint"
parser: ""
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - import
  - node
  - security
extends:
  - "@acme/eslint-config/import"
  - "@acme/eslint-config/node"
  - "@acme/eslint-config/recommended"
  - "@acme/eslint-config/security"
