env:
  node: true
  es6: true
globals:
  Atomics: false
  SharedArrayBuffer: false
overrides:
  - extends:
      - '@acme/eslint-config/typescript'
    files: [ '*.ts', '*.tsx' ]
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: './tsconfig.eslint.json'
    plugins:
      - '@typescript-eslint'
  - env:
      mocha: true
    extends:
      - '@acme/eslint-config/mocha'
    files: [ '*.test.js']
    plugins:
      - mocha
parser: ''
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - import
  - node
  - security
extends:
  - '@acme/eslint-config/import'
  - '@acme/eslint-config/node'
  - '@acme/eslint-config/recommended'
  - '@acme/eslint-config/security'
