env:
  node: true
  mocha: true
  es6: true
globals:
  Atomics: false
  SharedArrayBuffer: false
parser: ''
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - import
  - mocha
  - node
  - security
extends:
  - '@acme/eslint-config/import'
  - '@acme/eslint-config/mocha'
  - '@acme/eslint-config/node'
  - '@acme/eslint-config/recommended'
  - '@acme/eslint-config/security'
